#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import {formatDiagnostics, validateReport} from "./lib/report-validation.mjs";

const label = (value) => value.replaceAll("-", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

function evidenceText(evidence) {
  const location = evidence.path ?? evidence.url ?? evidence.kind;
  const lines = evidence.line == null ? "" : `:${evidence.line}${evidence.line_end && evidence.line_end !== evidence.line ? `-${evidence.line_end}` : ""}`;
  return `${location}${lines} — ${evidence.detail}`;
}

export function renderReport(report) {
  const validation = validateReport(report);
  if (!validation.valid) throw new Error(formatDiagnostics(validation.diagnostics));

  const lines = [
    `# Review Squad: ${label(report.mode)}`,
    "",
    report.summary.headline,
    "",
    "## Summary",
    "",
    `- Status: ${report.summary.overall_status}`,
    `- Critical: ${report.summary.critical_count}`,
    `- Important: ${report.summary.important_count}`,
    `- Minor: ${report.summary.minor_count}`,
    `- Not verified: ${report.summary.not_verified_count}`,
    `- Next move: ${report.summary.recommended_next_move}`,
    "",
    "## Findings",
    ""
  ];

  if (report.findings.length === 0) lines.push("No verified findings.", "");
  for (const finding of report.findings) {
    lines.push(`### ${finding.id} — ${finding.title}`, "", `Severity: ${finding.severity}`, "", finding.description, "", "Evidence:", "");
    for (const evidence of finding.evidence) lines.push(`- ${evidenceText(evidence)}`);
    lines.push("", `Suggested fix: ${finding.suggested_fix}`, "");
    if (finding.impact) {
      lines.push("Impact:", "");
      for (const key of ["runtime", "architecture", "delivery"]) if (finding.impact[key]) lines.push(`- ${label(key)}: ${finding.impact[key]}`);
      lines.push("");
    }
    if (finding.decision) {
      lines.push("Decision:", "", `- Owner: ${finding.decision.owner}`, `- Question: ${finding.decision.question}`, `- Consequence: ${finding.decision.consequence}`, `- Recommendation: ${finding.decision.recommendation}`, "");
    }
  }

  lines.push("## Not Verified", "");
  if (report.not_verified.length === 0) lines.push("Nothing was left unverified.", "");
  for (const item of report.not_verified) lines.push(`- ${item.item}: ${item.reason} (${item.source.join(", ")})`);
  if (report.not_verified.length) lines.push("");

  lines.push("## Mode Data", "", "```json", JSON.stringify(report.mode_data, null, 2), "```", "");

  if (report.extensions?.bmad) {
    const bmad = report.extensions.bmad;
    lines.push("## BMAD", "", `Extension schema: ${bmad.schema_version}`, "");
    if (bmad.installation) lines.push(`Installation: ${bmad.installation.kind} (${bmad.installation.manifest})`, "");
    for (const decision of bmad.decisions ?? []) lines.push(`- ${decision.finding_id}: ${decision.command} — ${decision.reason}`);
    if (bmad.decisions?.length) lines.push("");
    for (const diagnostic of bmad.diagnostics ?? []) lines.push(`- Diagnostic: ${diagnostic}`);
    if (bmad.diagnostics?.length) lines.push("");
  }

  lines.push("## Sources", "");
  for (const source of report.sources) lines.push(`- ${source.name} (${source.type})`);
  if (!report.sources.length) lines.push("No sources recorded.");
  lines.push("", "## Artifacts", "", `- Status: ${report.artifacts.status}`);
  if (report.artifacts.json_path) lines.push(`- JSON: ${report.artifacts.json_path}`);
  if (report.artifacts.markdown_path) lines.push(`- Markdown: ${report.artifacts.markdown_path}`);
  lines.push("", `Generated by ${report.generator.name} ${report.generator.version}.`, "");
  return lines.join("\n");
}

function usage() {
  return "Usage: node render-report.mjs <report.json> [--output <report.md>]";
}

if (process.argv[1] && path.basename(process.argv[1]) === "render-report.mjs" && new URL(import.meta.url).pathname === process.argv[1]) {
  const args = process.argv.slice(2);
  if (args.length === 1 && args[0] === "--help") {
    console.log(usage());
    process.exit(0);
  }
  const valid = (args.length === 1 && !args[0].startsWith("-")) || (args.length === 3 && !args[0].startsWith("-") && args[1] === "--output" && !args[2].startsWith("-"));
  if (!valid) {
    console.error(usage());
    process.exit(2);
  }
  try {
    const markdown = renderReport(JSON.parse(fs.readFileSync(args[0], "utf8")));
    if (args[2]) fs.writeFileSync(args[2], markdown);
    else process.stdout.write(markdown);
  } catch (error) {
    console.error(`RENDER_ERROR: ${error.message}`);
    process.exit(1);
  }
}
